language: groovy
sudo: false
jdk:
- oraclejdk8
script: ./update.sh
env:
  global:  	
    - secure: guKPRM1MFUyg9MSA9hpkTmaPDcS5Zyapf2zp8sXjmR+PAsWanIkNM+UU8menYslHG+EsJ3KEL0ctNVWGqBVtOdl6YeHH+Tw8oEcH4BWWALrQo1SR+Z/zaMawQpMyC6UCq6bLqGZoshnf4BZwOuPaP2OZpTc4s/MIrG1zH3/Tg+9ImoNP53bdS4l8hvWU7Wc0zWm2l7xL63uGI2bPx8voOGarRv2F4mL9COEdkeGMQYlpa0WXImSP2J+cWAWnL59p/9GYnErzmAK3Lg0RpW4/kt9XzXSHgFE520WDAvBgXe4ySBWAZUH3gA2/R6i3RCJToBcRnyEjwh1e/oeUOx8XFb2IRGc4RMp5FjCjlkfhr/q8MdyqwoGckY/PbMtju3zfU2KE7WzkreUKX45q1uzJYRVzuHxzdygDI7HLdhV4yavyek3tH1wskQScNWJP2ieEgF78r/DJYC3gicMu3IRf96s0oqaagWPf7AI9ffpPC4bh98H4amSzNMIQKSGGphcZZLxTVpC/FPvj5K56FpAhq4Nxr9WFHAhlTN6YD+c+0n+6UpwV8wP1GbSYKTVljr3u5QeXZj0L2ZwePDxMN/DT0I9VeaP1NVDQJY9oX839w1t1t4MpXnxV/JLc3EuLkouEAukJG64012pxLj/ivqKKOiTVbQTXs6nQkbttUTaEpc8=
    - GITHUB_REPO=ctoestreich/grails3-plugins
